version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./config_files:/app/config_files
      - ./internal/db/migrations:/app/internal/db/migrations
      - ./cmd:/app/cmd
      - ./Makefile:/app/Makefile
    depends_on:
      db:
        condition: service_healthy
    command: ["/api"]

volumes:
  db_data:


