env: "local"
server:
  host: "0.0.0.0"
  port: "8080"
  timeout: "5s"
  idle_timeout: "60s"
database:
  username: "your_user" # change to your db creds
  password: "password" # change to your db creds
  host: "db"
  port: "5432"
  name: "todolist" # change to your db creds
  ssl_mode: "disable"

